---
sudo: true

language: generic

services:
  - docker

script:
  - docker build -t securecodebox/engine:oss .
  - docker images

deploy:
  skip_cleanup: true
  -  provider: script
     script: deploy.sh
     on:
       branch: develop
  -  provider: script
     script: deploy.sh
     on:
       branch: master
