---
sudo: true

cache:
  directories:
  - .autoconf
  - $HOME/.m2

jobs:
  include:
    - stage: java test
      language: java
    - stage: build docker image
      language: generic
      services:
      - docker
      script:
      - docker build -t securecodebox/engine:oss .
      - docker images
      deploy:
        -  provider: script
           script: deploy.sh
           on:
             branch: develop

        -  provider: script
           script: deploy.sh
           on:
             branch: master
