---
sudo: true

language: java

services:
  - docker

cache:
  directories:
  - .autoconf
  - $HOME/.m2

before_script:
  - mvn validate -Pdependency-check

script:
  - echo -en "travis_fold:start:Test\r"
  - mvn test -q -B
  - echo -en "travis_fold:end:Test\r"
  - echo -en "travis_fold:start:Docker_Build\r"
  - docker build -t securecodebox/engine:oss .
  - echo -en "travis_fold:end:Docker_Build\r"
  - docker images

deploy:
  -  provider: script
     skip_cleanup: true
     script: bash deploy.sh
     on:
       branch: develop
  -  provider: script
     skip_cleanup: true
     script: bash deploy.sh
     on:
       branch: master
