---
sudo: true


jobs:
  include:
    - stage: java test
      language: java
    - stage: build docker image
      services:
      - docker
      script:
      - docker build -t securecodebox:oss .
      - docker images
