---
sudo: true

language: java

services:
  - docker

cache:
  directories:
  - .autoconf
  - $HOME/.m2

script:
  - mvn test
  - docker build -t securecodebox/engine:oss .
  - docker images

deploy:
  -  provider: script
     skip_cleanup: true
     script: bash deploy.sh
     on:
       branch: develop
  -  provider: script
     skip_cleanup: true
     script: bash deploy.sh
     on:
       branch: master
