---
sudo: true

language: generic

services:
  - docker

script:
  - docker build -t securecodebox/engine:oss .
  - docker images

deploy:
  -  provider: script
     skip_cleanup: true
     script: bash deploy.sh
     on:
       branch: develop
  -  provider: script
     skip_cleanup: true
     script: bash deploy.sh
     on:
       branch: master
