sudo: true
language: java
services:
- docker
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
install: true
script:
  - export REPO=securecodebox/engine
  - export TAG=$TRAVIS_BRANCH
  - echo -en "travis_fold:start:Docker_Build\r"
  - docker build -t $REPO:$TAG .
  - docker tag $REPO:$TAG $REPO:oss;
  - docker tag $REPO:$TAG $REPO:latest;
  - docker tag $REPO:$TAG $REPO:$TRAVIS_BUILD_NUMBER;
  - echo -en "travis_fold:end:Docker_Build\r"
  - docker images
  - echo -en "travis_fold:start:Test\r"
  - mvn install -Pdependency-check 
  - echo -en "travis_fold:end:Test\r"


deploy:
  -  provider: script
     skip_cleanup: true
     script: bash .travis/deployDockerHub.sh
     on:
       branch: develop
  -  provider: script
     skip_cleanup: true
     script: bash .travis/deployDockerHub.sh
     on:
       branch: master

before_install:
  - openssl aes-256-cbc -K $encrypted_e1e85fb8c151_key -iv $encrypted_e1e85fb8c151_iv
    -in .travis/security_at_iteratec-signing.key.enc -out .travis/security_at_iteratec-signing.key -d
    
