---
sudo: true
language: java

jobs:
  include:
    - stage: java test
    - stage: build docker image
      services:
      - docker
      script:
      - docker build -t securecodebox/engine:oss .
      - docker images

deploy:
  -  provider: script
     script: deploy.sh
     on:
       branch: develop

  -  provider: script
     script: deploy.sh
     on:
       branch: master
