version: '3'
services:
  engine:
    build: .
    depends_on:
      - camundadb
    ports:
      - "8080:8080"
    networks:
      - frontend
    labels:
      container_group: core
    environment:
      - CAMUNDA_BPM_DATABASE_TYPE=mysql
      - SPRING_DATASOURCE_URL=jdbc:mysql://camundadb:3306/${CAMUNDADB_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${CAMUNDADB_USER}
      - SPRING_DATASOURCE_PASSWORD=${CAMUNDADB_PW}
    restart: on-failure:3

  camundadb:
      image: mysql
      networks:
        - frontend
      volumes:
        - camundadb-datastore:/var/lib/mysql
      labels:
        container_group: infrastructure
      environment:
        - MYSQL_ROOT_PASSWORD=${CAMUNDADB_ROOT_PW}
        - MYSQL_DATABASE=${CAMUNDADB_DATABASE}
        - MYSQL_USER=${CAMUNDADB_USER}
        - MYSQL_PASSWORD=${CAMUNDADB_PW}

  scanner-infrastructure-nmap:
    build: ../scanner-infrastructure-nmap/.
    depends_on:
      - engine
    networks:
      - frontend
    labels:
      container_group: scanner
    environment:
      - ENGINE_ADDRESS=http://engine:8080/rest

networks:
  frontend:

volumes:
  camundadb-datastore: