# This value gets replaced by maven.
# default is prod, example for development:
# mvn spring-boot:run -Pdev
spring.profiles.active: ${activatedProfiles}

camunda.bpm:
  webapp:
    index-redirect-enabled: true

logging.level: INFO
logging.level.io.securecodebox: INFO

# Configure which persistence provider you would like to choose
# - none
# - elasticsearch
securecodebox.persistence.provider: none

# Configuration for the elasticsearch persistence provider:
securecodebox.persistence.elasticsearch.host: persistence-elasticsearch
securecodebox.persistence.elasticsearch.port: 9200
securecodebox.persistence.elasticsearch.index.prefix: securecodebox
