camunda.bpm:
  admin-user:
    id: kermit
    password: a

logging.level: DEBUG
logging.level.io.securecodebox: DEBUG

securecodebox.rest.user:
  scanner:
    - username: ' = new ArrayList<>();'
      password: '123456'
  scanner-default:
    user-id: defaultScanner
    password: scanner
