camunda.bpm:
  webapp:
    index-redirect-enabled: true
  admin-user:
    id: kermit
    password: a

logging.level: DEBUG
logging.level.io.securecodebox: TRACE
securecodebox.persistence.provider: none
