server:
  port: 8080
  ssl.enabled: false

camunda.bpm:
  admin-user:
    id: kermit
    password: a

logging.level: DEBUG
logging.level.io.securecodebox: TRACE

# Configure which persistence provider you would like to choose
# - none
# - elasticsearch
securecodebox.persistence.provider: none

securecodebox.rest.user.scanner-default:
  user-id: default-scanner
  password: scan
