# This value gets replaced by maven.
# default is prod, example for development:
# mvn spring-boot:run -Pdev
spring.profiles.active: ${activatedProfiles}

camunda.bpm:
  webapp.index-redirect-enabled: true
  authorization.enabled: true

logging.level: INFO
logging.level.io.securecodebox: INFO

# Configure which persistence provider you would like to choose
# - none
# - elasticsearch
securecodebox.persistence.provider: none

# Configuration for the elasticsearch persistence provider:
securecodebox.persistence.elasticsearch.host: persistence-elasticsearch
securecodebox.persistence.elasticsearch.port: 9200
securecodebox.persistence.elasticsearch.index.prefix: securecodebox
securecodebox.persistence.elasticsearch.index.delete_on_init: false

securecodebox.default.target.name: BodgeIT Public Host
securecodebox.default.target.location: bodgeit
securecodebox.default.target.uri: http://bodgeit:8080/bodgeit
securecodebox.default.context: BodgeIT

# Configure Secure CodeBox rest api protection
# - basic auth
# - none
securecodebox.rest.auth: basic auth

# Configure a technical user for the scanner services. This user allows the scanner services to authenticate on the engines rest api.
# (if not configured, a user has to be added manually in the camunda ui)
securecodebox.rest.user.scanner-default:
  user-id:
  password:
